lang: ru
arenas:
  spleef:
    world: world
    minPlayers: 3
    maxPlayers: 10
    startCoords:
      x: 1294.5
      y: 97
      z: -377.5
    blockToBreak: SNOW_BLOCK
    startItem: DIAMOND_SPADE
    startCd: 10
    startCdReset: false
    winAmount: 50
