main: ru.zemf4you.wgspleef.SpleefPlugin
name: WGSpleef
version: '1.0'
description: Spleef plugin with regions from WG and
load: POSTWORLD
author: zemf4you
website: vk.com/zemf4you
depend: [WorldGuard, WorldEdit, Vault]
commands:
  spleef:
    description: Spleef command
#    aliases:
#      - foobar
#      - fubar
#    permission: test.foo
#    permission-message: You do not have permission!
    usage: /spleef
#permissions:
#  test.foo:
#    description: Allows foo command
#    default: op
#  test.*:
#    description: Wildcard permission
#    default: op
#    children:
#      test.foo: true