lang: ru
arenas:
  spleef:
    world: world
    minPlayersCount: 3
    maxPlayersCount: 10
    startCoords:
      x: 1294.5
      y: 97
      z: -377.5
    blockToBreak: SNOW_BLOCK
    startItem: DIAMOND_SPADE
    startCountdown: 10
    startCountdownReset: false
    reward: 50
